### ISSUE TITLE
Feature request: support multiple, last-wins, #@include directives in multi_properties

### ISSUE THREAD

**Issue by drbenmorgan** [BxCppDev/Bayeux#53]
With the doc updates from #42, I've tried out the `#@include` directive in properties and multi_properties. My thought was that these might support simple inclusion of configuration, which can then be overridden on a section/property basis. The use case is in SuperNEMO, where multi_properties files are used to define the processing pipeline. If a user wants to write there own pipeline, but just modify a few parameters from a "standard" script, they have to copy that entire script, locate the parameters, and change them. If they're exploring a range of values, they will end up with a large number of scripts only differing by one or two lines. That can be difficult to manage, confusing, and error prone.

Instead, it would be more useful to allow *inclusion* of other scripts to provide a base configuration that can then be overridden in as many places as required. For example, let's say our base configuration is the`multi_properties`:

```ini
#@description SuperNEMO demonstrator official reconstruction configuration
#@key_label  "name"
#@meta_label "type"
 
[name="config" type="section"]
foo : string = "default"
bar : real = 3.14

# much more configuration follows...
```

If a user now wants to modify the `foo` parameter, they should be able to do:

```ini
#@description My config
#@key_label "name"
#@meta_label "type"

#@include "supernemo.conf"

[name="config" type="section"]
foo : string = "overriden"
```

The expected result would then be the `multi_properties` object resulting from `supernemo.conf` with the `config.foo` parameter changed to "overridden".  

It should also support multiple inclusion, e.g.

```ini
#@description My config
#@key_label "name"
#@meta_label "type"

#@include "supernemo_config.conf"
#@include "supernemo_services.conf"

...
```

It should also allow the `multi_properties::reader` class to use a path based lookup of files given to `#@include` directives so that clients can define this and allow overriding, e.g. given a filesystem layout like:

```
+- defaults/
|  +- foo.conf
|  +- bar.conf
+- user/
   +- foo.conf
```

Then given a path like `SNEMO_CONFIG_INCLUDE_PATH=/some/prefix/user:/some/prefix/defaults`, reading a multi_properties file written as:

```ini
#@description My config
#@key_label "name"
#@meta_label "type"

#@include "foo.conf"
#@include "bar.conf"

...
```

would result in the inclusion of `/some/prefix/user/foo.conf` and `/some/prefix/defaults/bar.conf`.

This behaviour should also be extended to `properties`, where `#@include` works, but only as a one-shot operation. For example, the properties read from

```ini
#@include "other.conf"
foo : string = "overriden"
```

will not result in the `foo` parameter being set or overriden. The same is true when used under a `multi_properties` section.

Adding this functionality would benefit and simplify ongoing work in SuperNEMO.

**Comment by fmauger** [comment]
I will consider this idea ASAP. I think I could need such a feature on my side too.
Cheers

**Comment by fmauger** [comment]
I'm currently exploring a way to implement these functionalities. The idea is to segment the problem in three aspects:
a - new merging methods on both properties and multi_properties classes with special option to accept/reject overiden keys/sections.
Note that the merging is valid only if matching keys correspond to the same type of properties : boolean, int, real, string plus additional traits like unit support or path flag for properties and key_label, meta_label and meta value for sections in multi_properties
 
b - new include file path resolver with env var support (a la PATH=foodir:bardir) but the user can choose the name of the env (i.e. "SNEMO_CONFIG_INCLUDE_PATH")

c - support a new "#@include blah" directive in the parser (plus additional path lookup setting directives)

Points a and b are now done and working as far as I can test and see. 
Now I have to implement c in the proper way, particularly ensuring proper behaviour of the concept under recursive file inclusion.
A question arises from this last consideration:
assuming file A includes file B (A<-B) which in turn includes file C (B<-C), and A uses dedicated lookup settings to resolve B path, should we use the same A<-B lookup for B<-C ? 
My feeling is no. Because B<-C has been likely designed without any knowledge
of A needing B so that the B<-C lookup is some kind of private relationship that A should completely ignore.

**Comment by drbenmorgan** [comment]
> A question arises from this last consideration:
> assuming file A includes file B (A<-B) which in turn includes file C (B<-C), and A uses dedicated lookup settings to resolve B path, should we use the same A<-B lookup for B<-C ?
> My feeling is no. Because B<-C has been likely designed without any knowledge
> of A needing B so that the B<-C lookup is some kind of private relationship that A should completely ignore.

My suggestion would be to follow the same logic as used by `#include` directives in C/C++ or `import` in Python. Those are simple and understandable. I wouldn't allow any special directive for resolving paths other than absolute paths or relative paths plus a `PATH` style variable.

**Comment by fmauger** [comment]
Yes, I had this kind of thing in mind and in fact have started to consider to mimic the #include behaviour. We are on the same page I guess. So I continue in this direction.

**Comment by fmauger** [comment]
Bayeux 3.4.2 will provide such a mechanism. To be checked ASAP and eventually adapted if buggy or missing features.
